#!/bin/bash

docker kill graphite
docker rm graphite
truncate ./logs/* --size 0

docker run -d -v $(pwd)/logs:/var/log/supervisor -p 8127:80 -p 8125:8125/udp -p 8126:8126 -p 2003:2003/udp --name graphite olx-inc/graphite
